on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: "Checkout Code" 
        uses: actions/checkout@v2
      - name: "Install go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: "Build Binaries"
        run: |
          mkdir -p ./release/jas-win-${{github.ref_name}}
          mkdir -p ./release/jas-mac-${{github.ref_name}}
          mkdir -p ./release/jas-linux-${{github.ref_name}}
          GOOS=linux GOARCH=amd64 go build -o ./release/jas-linux-${{github.ref_name}}/jas
          GOOS=windows GOARCH=amd64 go build -o ./release/jas-win-${{github.ref_name}}/jas.exe
          GOOS=darwin GOARCH=amd64 go build -o ./release/jas-linux-${{github.ref_name}}/jas
          tar -zcvf jas-linux-${{github.ref_name}}.tar.gz ./release/jas-linux-${{github.ref_name}}
          tar -zcvf jas-win-${{github.ref_name}}.tar.gz ./release/jas-win-${{github.ref_name}}
          tar -zcvf jas-mac-${{github.ref_name}}.tar.gz ./release/jas-mac-${{github.ref_name}}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz